version: 2
jobs:
  build:
    working_directory: ~/app-name
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: display-current-dir
          command: pwd
      - run:
          name: install-dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
            - ./node_modules
      - run:
          name: list-current-dir
          command: ls
      - run:
          name: angular-build
          command: node_modules/angular-cli/bin/ng build --prod
      - run:
          name: angular-test
          command: node_modules/angular-cli/bin/ng test --watch=false --browsers=ChromeHeadless
      # - run:
      #     name: angular-lint
      #     command: yarn lint